<<<<<<< HEAD
# Site settings
name: 细雨邻家
email: lxf@cumt.edu.cn
author: Lei Xiaofeng
url: drizzletown.github.io
resume_site: drizzletown.github.io
github: https://github.com/drizzletown/drizzletown.github.io
baseurl: ""
description: Actually, less is more!
meta_description: 
motto: It's our wits that make us men.
banner: 自由 平等 宽容 自律。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: drizzletown

# Build settings
markdown: kramdown

=======
theme: jekyll-theme-leap-day

